#!/bin/bash
{MODULES}

getarg(){
    count=$1
    shift
    echo $(eval "echo \$$count")
}
ARGLEN=$#

STR_PRINT=""
STR_PRINT="&> /dev/null"
str(){
    CMD=$1
    shift
    if [[ $CMD == "eq" ]]; then
        if [[ $1 == $2 ]]; then
            return 0
        else
            return 1
        fi
    elif [[  "contains cont" =~ $CMD ]]; then
        if [[ $1 == *$2* ]]; then
            return 0
        else
            return 1
        fi
    elif [[ $CMD == "len" ]]; then
        echo ${#@}
    elif [[ $CMD == "cat" ]]; then
        echo "$@"
    fi
    return $?

}





main(){




}

main $@


