#!/bin/bash
#creates and adds predefined files to the current directory/project with modules and imports

get(){
    # echo "GETTING $1 $2"
    local URI="https://raw.githubusercontent.com/cswaltzinger/code-bases/main/$1/$2.$1"
    curl -s $URI 
}


createFile(){
    local FILE=$1

    local LANG="${FILE##*.}"
    local NAME="${FILE%%.*}"
    local NAME=$(basename $NAME)

    if [[ "$FILE" != *"."* ]]; then
        LANG="sh"
    fi

    if [[ "Makefile makefile" =~ $NAME ]];then 
        local MAKEFILE="main"
        if [ "$LANG" = "large" ];then
            MAKEFILE="large"
        fi
        get makefile large > $FILE 
        return $?
    fi
    get $LANG main > $FILE 


}


main(){
    for FILE in "$@"; do 
        createFile $FILE
    done
}




main "$@"



