#!/bin/bash
convRegex(){
    TOECHO="$1"
    shift
    for i in $@;do
        if [ "$1" ];then
            TOECHO="$TOECHO|$i"
        fi
    done
    echo -n "$TOECHO"
}


IMAGES=$(convRegex $(data get docker hidden-images))
VOLUMES=$(convRegex $(data get docker hidden-volumes))
NETWORKS=$(convRegex $(data get docker hidden-networks))

filter(){
    FILTER_OPTS="$1"
    shift


    case "$1" in
        run|exec|top|logs|inspect)
            docker $@

            return 0
            ;;
        --all|all)
            shift 
            docker $@
            return 0 
            ;;
        *)

        ;;

    esac
    case "${@:$#:1}" in
        -a|--all|-h|--help|help) 
            docker $@
            return 0 
            ;;
        *)
            
            ;;
    esac


    # echo docker $@
    OUTPUT=$(docker $@ )
    HEADDER=$(echo "$OUTPUT" | head -n 1)
    OUTPUT=$(echo "$OUTPUT" | tail -n +2)
    echo "$HEADDER" 
    echo "$OUTPUT" | eval $FILTER_OPTS
    # while read -r line; do
    #     if [[ "$line" =~ $IMAGES || "$line" =~ $VOLUMES || "$line" =~ $NETWORKS]]; then
    #         continue
    #     fi
        
    #     echo "$line"
    # done <<< "$OUTPUT"
}

case "$1" in 
    -f|--filter|filter)
        shift
        # echo "[$1]"
        filter "$@"
        ;;
    *)
        docker $@
        ;;
esac


