#!/bin/bash

# github util functions used to help admin a directory of git repos 
# originally used when grading student labs to pull all repos, run tests, and push results




if [ "$GUTIL_LS_CMD" = "" ];then
    GUTIL_LS_CMD="ls -d */.git"
fi


#github util functions 
#current working directory saved as var 
TWD=$(realpath $(pwd))

# echo function to seperate output 
function eten(){
    echo "------------------------------"
    echo "" && echo "" && echo "" && echo ""
}


# go through each git repo in current directory and run a command
function it(){
    IT_DIR=$(pwd)
    for name in $($GUTIL_LS_CMD );do
        name=$(dirname $name)
        echo $name &&
        cd $name &&
        eval $@ ;
        cd $IT_DIR
    done
    
}

# basic git functions run for all repos in current directory  
function pull(){
    it git pull 
}
function fetch(){
    it git fetch 
}
function status(){
    it git status    
}


# commit all changes in each students repo and push to remote with message as argument 
function push(){
    message="$@"
    if [[ "$message" = "" ]];then
        message="lab graded"
    fi

    for name in $(ls -d */.git );do
        #cd $name && 
        name=$(dirname $name)
        echo "" 
        echo $name 
        cd $name && 
        #git add . && 
        # git commit -m $message && 
        # git push 
        echo $message
        cd $TWD 
    done
}

function next(){
    NAME=""
    for name in $(ls  */ntg );do
        NAME=$(dirname $name) 
        cd $NAME
        #echo $(pwd)
        rm ntg 
        break
    done
    echo "$NAME"
}




$@

