#!/bin/bash
return 0 
CDIR="$HOME/.term_settings"
if [ "$XDG_CONFIG_HOME" ];then 
    CDIR="$XDG_CONFIG_HOME/term_settings"
fi

if [ -d "$CDIR" ];then
    :
else
    mkdir -p "$CDIR"
fi

SFILE="$CDIR/settings"
if [ -f "$SFILE" ];then
    :
else
    echo "" >> "$SFILE"
fi

lower_case_code='
i = inp.split("=")
name = i[0].strip()
value = i[1].strip()
sep="\n\t"
'
CYAN=$(data get colors cyan)
RED=$(data get colors red)
RESET=$(data get colors reset)

case "$COLOR_PRINT" in 
    always|true|yes|y) 
        ;;
    auto)
        if [ -t 1 ];then
            :
        else
            CYAN="";RED="";RESET=""
        fi
        ;;
    0|false|no|n|never) 
        CYAN="";RED="";RESET=""
        ;;
    *) ;;
esac


lower_case_code=$(
    echo  "$lower_case_code" ;
    echo "if len(value) < ($(tput cols)-5):";
    echo -e "\tsep=\"\\t\"";
    echo "print(f\"$CYAN{name.lower()}{sep}$RED{value}\")"
    )


get(){
    local after=""
    case $1 in 
        --name|-n) 
            after="inp.split(\"=\")[0].strip()"
            shift
            ;;
        --value|-v)
            after="printif index==0 , inp.split(\"=\")[1].strip()"
            shift
            ;;
        *)
            after="inp"

    esac 
    local query="$@"
    if [ -z "$query" ];then
        query="True"
    else 
        # query="\"$query\".replace(\" \",\"_\").replace(\"/\",\"_\").lower() in inp.lower()[:inp.index(\"=\")]"
        query="\"$(echo "$query" | tr ' /' '__' )\".lower() in inp.lower()[:inp.index(\"=\")]"
        # echo "____$query ____"
    fi
    
    env |sort|  pawk "$query" | pawk "$after" 
}



set(){
    while [ $# -gt 0 ]; do
        local inp="$1"
        if [[ "$inp" == *"="* ]];then
            local name=$(echo "$inp" | cut -d= -f1 | tr '[:lower:]' '[:upper:]' | tr ' /' '__')
            local value=$(echo "$inp" | cut -d= -f2-)
            # export "$name"="$value"
            echo -e "$CYAN$name$RESET=$RED$value$RESET"
        else
            # local name=$(echo "$inp" |tr '[:lower:]' '[:upper:]' | tr ' /' '__')
            local value="$2"
            local name="$inp"
            
            
            
            if [ "$name" = '--rm' ];then
                value=$(echo "$value" |tr '[:lower:]' '[:upper:]')
                echo "Removing $CYAN$value"
                unset "$value"
            else 
                name=$(echo "$inp" |tr '[:lower:]' '[:upper:]' | tr ' /' '__')
                eval "export $name=$value"
            fi 
            shift
        fi
        shift
    done
    
}

reset(){
    if [ -z "$BARE_ENV" ]; then 
        echo nothing to reset
        return
    else 
        echo "Resetting to bare env"
        echo -e "$BARE_ENV "
    fi
}


save(){
    local CUR_ENV=$(env | sort ) 
    local SENV=""
    BARE_ENV=$(cat ~/.bareenv | sort)
    diff <(echo "$CUR_ENV") <(echo "$BARE_ENV") 
    #| grep '^+' | sed 's/^+//' | pawk "$lower_case_code" > "$SFILE"
}

ep(){
    echo $PATH | tr : "\n"|sort | grep brew
}


$@
