#!/bin/bash

#exexutionor for pawk, a python awk like tool
new_args=""
for arg in "$@"; do
    if [ -n "$new_args" ];then
        new_args="$new_args '$arg'"
    else
        new_args="'$arg'"
    fi
done
#clear
eval "python3 ~/bin/static/pawk.py $new_args"

